version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    container_name: agencia-viagens-db
    environment:
      POSTGRES_DB: agencia_viagens
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - agencia-network

volumes:
  postgres_data:

networks:
  agencia-network:
    driver: bridge
